"""Single sanitized v6 configuration contract; generated native data is checked."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT/'docs/candidate-parity-contract.json'
HEADER = ROOT/'scripts/candidate_contract.generated.h'


# 1080p, 1440p and 4K, each in 16:9 (monitors and TVs) and 16:10 (MacBook screens).
# The window driver lists the same sizes on every display they fit (display.c).
RESOLUTIONS = [[1920, 1080], [1920, 1200], [2560, 1440], [2560, 1600], [3840, 2160], [3840, 2400]]


def load():
    value = json.loads(PATH.read_text())
    if (value['schema'] != 1 or value['supported_resolutions'] != RESOLUTIONS
            or value['default_resolution'] not in RESOLUTIONS):
        raise ValueError('Unsupported candidate contract')
    # MetalFX upscaling (1.3): its environment turns on what the contract's own leaves off (DXMT's
    # NVIDIA identity; the d3d12, DLSS and NVAPI stand-ins); sharpening is DXMT's amount per choice.
    if (set(value['metalfx_environment']) != {'DXMT_ENABLE_NVEXT', 'WINEDLLOVERRIDES'}
            or set(value['metalfx_sharpening']) != {'low', 'high'}
            or not all(0 < float(amount) <= 1 for amount in value['metalfx_sharpening'].values())):
        raise ValueError('Unsupported candidate contract')
    if hashlib.sha256((ROOT/value['renderer_profile']).read_bytes()).hexdigest() != value['renderer_profile_sha256']:
        raise ValueError('Candidate renderer profile changed without review')
    return value


def launch_preferences(height=1200, width=1920):
    contract = load()
    if [width, height] not in contract['supported_resolutions']:
        raise ValueError('Unsupported resolution: ' + f'{width}x{height}')
    return contract['launch_preferences'] | {'FullScreenWidth': str(width), 'WindowedWidth': str(width),
                                             'FullScreenHeight': str(height), 'WindowedHeight': str(height)}


def native_header():
    contract = load()
    quoted = lambda text: '@' + json.dumps(text)
    lines = ['/* Generated by candidate_contract.py; edit the JSON contract instead. */',
             '#define CANDIDATE_PROFILE '+quoted(contract['profile']),
             '#define CANDIDATE_CONTRACT_SHA256 '+quoted(hashlib.sha256(PATH.read_bytes()).hexdigest()),
             '#define CANDIDATE_DEFAULT_WIDTH '+str(contract['default_resolution'][0]),
             '#define CANDIDATE_DEFAULT_HEIGHT '+str(contract['default_resolution'][1]),
             'static NSArray *candidateResolutions(void) { return @['+
             ','.join('@[@%d,@%d]' % (w, h) for w, h in contract['supported_resolutions'])+']; }']
    for key, name in [('launch_preferences', 'candidateLaunchPreferences'),
                      ('baseline_preferences', 'candidateBaselinePreferences'),
                      ('environment', 'candidateEnvironment'),
                      ('metalfx_environment', 'candidateMetalFXEnvironment'),
                      ('metalfx_sharpening', 'candidateMetalFXSharpening')]:
        entries = ','.join(quoted(k)+':'+quoted(v) for k,v in sorted(contract[key].items()))
        lines.append('static NSDictionary *'+name+'(void) { return @{'+entries+'}; }')
    return '\n'.join(lines)+'\n'


def verify_generated():
    if not HEADER.is_file() or HEADER.read_text() != native_header():
        raise ValueError('Regenerate the native candidate contract with scripts/candidate_contract.py')


if __name__ == '__main__':
    HEADER.write_text(native_header())
