/* Generated by candidate_contract.py; edit the JSON contract instead. */
#define CANDIDATE_PROFILE @"v1.0"
#define CANDIDATE_CONTRACT_SHA256 @"1341e680ced5f228468e43ccd73e46362fab2844530e9918c8b17e066b2a6da3"
#define CANDIDATE_DEFAULT_WIDTH 1920
#define CANDIDATE_DEFAULT_HEIGHT 1200
static NSArray *candidateResolutions(void) { return @[@[@1920,@1080],@[@1920,@1200],@[@2560,@1440],@[@2560,@1600],@[@3840,@2160],@[@3840,@2400]]; }
static NSDictionary *candidateLaunchPreferences(void) { return @{@"DynamicRenderScale":@"0",@"FullScreenHeight":@"1200",@"FullScreenRefresh":@"120",@"FullScreenWidth":@"1920",@"FullscreenWindow":@"0",@"FullscreenWindowEnabled":@"0",@"UseCustomWorldScale":@"1",@"WindowMode":@"0",@"WindowedFullscreen":@"0",@"WindowedHeight":@"1200",@"WindowedPosX":@"100",@"WindowedPosY":@"100",@"WindowedWidth":@"1920"}; }
static NSDictionary *candidateBaselinePreferences(void) { return @{@"FrameRateCap":@"600",@"GFXPresetLevel":@"1",@"PhysicsQuality":@"3",@"ShowFPSCounter":@"1",@"ShowRTT":@"1",@"UseCustomFrameRates":@"1",@"VerticalSyncEnabled":@"0",@"WindowedRefresh":@"120"}; }
static NSDictionary *candidateEnvironment(void) { return @{@"CX_ACTIVE_GRAPHICS_BACKEND":@"dxmt",@"CX_GRAPHICS_BACKEND":@"dxmt",@"DXMT_CANVAS_DRAWABLES":@"3",@"DXMT_CANVAS_OVERLAY":@"0",@"DXMT_PIPELINE_CACHE_NAMESPACE":@"ow2-source-v1",@"DXMT_PIPELINE_CACHE_PREFER_EXPENSIVE":@"1",@"DXMT_PIPELINE_CACHE_PREWARM_LIMIT":@"128",@"DXMT_PIPELINE_CACHE_PREWARM_MS":@"10000",@"DXMT_PREPARE_SHADERS":@"1",@"DXMT_USE_DEFAULT_METAL_CACHE":@"1",@"ROSETTA_ADVERTISE_AVX":@"1",@"WINEDLLOVERRIDES":@"d3d11,dxgi,d3d10core,winemetal=b;d3d12=",@"WINEESYNC":@"0",@"WINEMAC_MOUSELOOK":@"Overwatch.exe",@"WINEMSYNC":@"1",@"WINE_GAME_MODE":@"Overwatch.exe",@"WINE_SIMULATE_WRITECOPY":@"1"}; }
